-- // Initializes the physical world

local WorldService = {}

--------------------------------------------------------------------------------------------------------------------------------------------------------
-- Local

--------------------------------------------------------------------------------------------------------------------------------------------------------
-- Public

--------------------------------------------------------------------------------------------------------------------------------------------------------
-- Init

function WorldService._init()
    print("World service initialized")
    --> CREATE 50x50 STUDS PLATFORM FOR ENEMIES TO SPAWN ON
end

function WorldService._start()
    print("World service started")
end

return WorldService